INSERT INTO TODO(ID, USERNAME, DESCRIPTION, TARG_DATE, DONE)
VALUES(1001,'uttu', 'JOPADJAPOSDJ',CURRENT_DATE(), false);

INSERT INTO TODO(ID, USERNAME, DESCRIPTION, TARG_DATE, DONE)
VALUES(1004,'uttu', 'JOPADJAPOSDJ',CURRENT_DATE(), false);

INSERT INTO TODO(ID, USERNAME, DESCRIPTION, TARG_DATE, DONE)
VALUES(1002,'uttu', 'JOPADJAPOSDJ',CURRENT_DATE(), false);

INSERT INTO TODO(ID, USERNAME, DESCRIPTION, TARG_DATE, DONE)
VALUES(1003,'uttu', 'JOPADJAPOSDJ',CURRENT_DATE(), false);
